// Catálogo extendido de escalas para Modelos Sonoros: Música tonal.
// Cada escala tiene: nombre principal, alias, familia (color), intervalos en semitonos,
// fórmula intervalica (1-b2-3...), descripción, origen, géneros, obras, relaciones.
//
// IMPORTANTE: el array intervals incluye los semitonos de cada grado desde la tónica,
// NO incluye la octava (12). Para tocar la escala ascendente y descendente,
// la octava se añade automáticamente.

export const SCALE_FAMILIES = {
  diatonic: { label: "Diatónicas y menores", color: "ink" },
  majorModes: { label: "Modos del mayor", color: "ink" },
  melodicMinorModes: { label: "Modos del menor melódico", color: "mint" },
  harmonicMinorModes: { label: "Modos del menor armónico", color: "lime" },
  pentatonic: { label: "Pentatónicas", color: "lime" },
  hexatonic: { label: "Hexáfonas", color: "mint" },
  octatonic: { label: "Octatónicas y bebop", color: "mint" },
  messiaen: { label: "Modos de Messiaen", color: "lime" },
  synthetic: { label: "Sintéticas y exóticas", color: "lime" },
  worldApprox: { label: "Aproximaciones no-occidentales", color: "ink" },
};

export const SCALES = [
  // ===== DIATÓNICAS BÁSICAS =====
  {
    id: "major",
    name: "Mayor",
    aliases: ["Jónico", "Bilawal (raga)"],
    family: "diatonic",
    intervals: [0, 2, 4, 5, 7, 9, 11],
    formula: "1 - 2 - 3 - 4 - 5 - 6 - 7",
    description: "Escala diatónica mayor: dos tetracordes idénticos (T-T-S) separados por un tono.",
    origin:
      "Base de la armonía tonal occidental desde el siglo XVII. Codificada en la teoría como referente.",
    genres: ["Música tonal occidental", "Pop", "Jazz", "Folklore mayoritario"],
    works: ["Mozart – cualquier sonata mayor", "The Beatles – Let It Be"],
    relations: ["Genera los siete modos diatónicos por rotación."],
    level: 1,
  },
  {
    id: "naturalMinor",
    name: "Menor natural",
    aliases: ["Eólico", "Asavari (raga)"],
    family: "diatonic",
    intervals: [0, 2, 3, 5, 7, 8, 10],
    formula: "1 - 2 - b3 - 4 - 5 - b6 - b7",
    description: "Escala menor sin alteraciones cromáticas. Forma descendente del menor melódico.",
    origin:
      "Estructura modal heredada del eólico medieval. Convive con la armónica y la melódica en la práctica común.",
    genres: ["Tonal occidental", "Folk", "Rock modal"],
    works: ["Albéniz – Asturias (Leyenda)", "Radiohead – Karma Police"],
    relations: ["Es el modo eólico del mayor. Comparte tetracordes con dórico y frigio."],
    level: 1,
  },
  {
    id: "harmonicMinor",
    name: "Menor armónica",
    aliases: ["Menor con sensible", "Bhairavi (variante)"],
    family: "diatonic",
    intervals: [0, 2, 3, 5, 7, 8, 11],
    formula: "1 - 2 - b3 - 4 - 5 - b6 - 7",
    description: "Menor con sensible alzada. Intervalo de segunda aumentada entre b6 y 7.",
    origin:
      "Surge en la práctica común para tener un acorde de dominante mayor (V) en el menor. La segunda aumentada le da color oriental.",
    genres: ["Tonal occidental", "Música clásica menor", "Klezmer", "Heavy metal neoclásico"],
    works: [
      "Mozart – Sinfonía Nº40 (cadencias)",
      "Yngwie Malmsteen – cualquier pasaje neoclásico",
    ],
    relations: ["Genera por rotación al frigio dominante (V grado) y al lidio #2 (VI grado)."],
    level: 1,
  },
  {
    id: "melodicMinorAsc",
    name: "Menor melódica asc.",
    aliases: ["Menor melódica jazz", "Hindú menor"],
    family: "diatonic",
    intervals: [0, 2, 3, 5, 7, 9, 11],
    formula: "1 - 2 - b3 - 4 - 5 - 6 - 7",
    description: "Forma ascendente: solo la tercera es menor; el resto coincide con la mayor.",
    origin:
      "Se usa en la práctica común solo en sentido ascendente; en jazz, se mantiene en ambos sentidos como escala modal completa.",
    genres: ["Tonal occidental ascendente", "Jazz modal", "Cool jazz"],
    works: ["Wayne Shorter – temas modales", "Coltrane – exploraciones modales"],
    relations: ["Genera la escala alterada (modo VII) y lidio dominante (modo IV)."],
    level: 1,
  },

  // ===== MODOS DEL MAYOR (excluyendo jónico/eólico ya cubiertos) =====
  {
    id: "dorian",
    name: "Dórico",
    aliases: ["Modo II del mayor", "Kafi (raga)"],
    family: "majorModes",
    intervals: [0, 2, 3, 5, 7, 9, 10],
    formula: "1 - 2 - b3 - 4 - 5 - 6 - b7",
    description: "Modo menor con sexta mayor. Simétrico: T-S-T-T-T-S-T.",
    origin:
      "Modo eclesiástico medieval. Central en jazz modal por su sonoridad menor abierta y luminosa.",
    genres: ["Jazz modal", "Folk celta", "Música medieval", "Funk"],
    works: [
      "Miles Davis – So What",
      "Simon and Garfunkel – Scarborough Fair",
      "Daft Punk – Get Lucky",
    ],
    relations: ["Es modo II del mayor. Comparte tonos con eólico salvo la 6 alzada."],
    level: 2,
  },
  {
    id: "phrygian",
    name: "Frigio",
    aliases: ["Modo III del mayor", "Bhairavi (raga)"],
    family: "majorModes",
    intervals: [0, 1, 3, 5, 7, 8, 10],
    formula: "1 - b2 - b3 - 4 - 5 - b6 - b7",
    description: "Modo menor con segunda menor descendente. Carácter oscuro, andaluz, español.",
    origin:
      "Modo eclesiástico. Sobrevive en el flamenco vía la modalidad andaluza (con tercera mayor sería frigio dominante).",
    genres: ["Flamenco modal", "Metal extremo", "Música medieval"],
    works: ["Albéniz – Iberia (gestos andaluces)", "Black Sabbath – Symptom of the Universe"],
    relations: ["Es modo III del mayor. Su variante con 3 mayor es el frigio dominante (menor armónico V)."],
    level: 2,
  },
  {
    id: "lydian",
    name: "Lidio",
    aliases: ["Modo IV del mayor", "Kalyan (raga)", "Yaman"],
    family: "majorModes",
    intervals: [0, 2, 4, 6, 7, 9, 11],
    formula: "1 - 2 - 3 - #4 - 5 - 6 - 7",
    description: "Modo mayor con cuarta aumentada. Tritono de la tónica al cuarto grado.",
    origin:
      "Modo eclesiástico. Reconquistado en el siglo XX como escala de tónica luminosa y suspendida.",
    genres: ["Música clásica del XX", "Jazz modal", "Film scoring", "Pop atmosférico"],
    works: [
      "Debussy – Cathédrale engloutie",
      "John Williams – Star Wars (temas mayores)",
      "Joe Satriani – Flying in a Blue Dream",
    ],
    relations: ["Es modo IV del mayor. Su acorde-tónica natural es Maj7#11."],
    level: 3,
  },
  {
    id: "mixolydian",
    name: "Mixolidio",
    aliases: ["Modo V del mayor", "Khamaj (raga)"],
    family: "majorModes",
    intervals: [0, 2, 4, 5, 7, 9, 10],
    formula: "1 - 2 - 3 - 4 - 5 - 6 - b7",
    description: "Modo mayor con séptima menor. La escala natural del acorde dominante.",
    origin:
      "Modo eclesiástico. Central en el blues, el rock y el folk anglosajón.",
    genres: ["Blues", "Rock clásico", "Country", "Folk"],
    works: ["The Beatles – Norwegian Wood", "Led Zeppelin – numerosos pasajes"],
    relations: ["Es modo V del mayor. Sobre acorde de dominante 7."],
    level: 2,
  },
  {
    id: "locrian",
    name: "Locrio",
    aliases: ["Modo VII del mayor"],
    family: "majorModes",
    intervals: [0, 1, 3, 5, 6, 8, 10],
    formula: "1 - b2 - b3 - 4 - b5 - b6 - b7",
    description: "Modo más oscuro. Quinta disminuida desde la tónica. No establece tónica estable.",
    origin:
      "Modo teórico durante siglos. Usado en jazz modal contemporáneo y metal extremo.",
    genres: ["Metal extremo", "Jazz modal avanzado"],
    works: ["Björk – Army of Me (pasajes)", "Repertorio metal"],
    relations: ["Es modo VII del mayor. Su acorde-tónica es ø7."],
    level: 4,
  },

  // ===== MODOS DEL MENOR MELÓDICO =====
  {
    id: "dorianb2",
    name: "Dórico b2",
    aliases: ["Frigio #6", "Modo II del menor melódico", "Phrygian #6"],
    family: "melodicMinorModes",
    intervals: [0, 1, 3, 5, 7, 9, 10],
    formula: "1 - b2 - b3 - 4 - 5 - 6 - b7",
    description: "Frigio con sexta mayor: tensión oriental con base menor abierta.",
    origin: "Modo del menor melódico ascendente. Color del jazz fusión modal.",
    genres: ["Jazz modal", "Fusión"],
    works: ["John McLaughlin – pasajes modales"],
    relations: ["Modo II del menor melódico. Combina sonoridades frigias y dóricas."],
    level: 6,
  },
  {
    id: "lydianAug",
    name: "Lidio aumentado",
    aliases: ["Modo III del menor melódico"],
    family: "melodicMinorModes",
    intervals: [0, 2, 4, 6, 8, 9, 11],
    formula: "1 - 2 - 3 - #4 - #5 - 6 - 7",
    description: "Lidio con quinta aumentada. Sonoridad expresionista, tensa pero luminosa.",
    origin: "Modo III del menor melódico. Usado en jazz modal y composición postonal.",
    genres: ["Jazz modal", "Música del XX"],
    works: ["Wayne Shorter – pasajes modales", "Scriabin – obras tardías"],
    relations: ["Modo III del menor melódico. Acorde-tónica: aumMaj7."],
    level: 6,
  },
  {
    id: "lydianDom",
    name: "Lidio dominante",
    aliases: ["Mixolidio #11", "Modo IV del menor melódico", "Bartók"],
    family: "melodicMinorModes",
    intervals: [0, 2, 4, 6, 7, 9, 10],
    formula: "1 - 2 - 3 - #4 - 5 - 6 - b7",
    description: "Mixolidio con cuarta aumentada. Sonoridad acrobática del jazz moderno.",
    origin: "Modo IV del menor melódico. Bartók la usa rutinariamente como 'escala acústica'.",
    genres: ["Jazz moderno", "Bartók", "Folk húngaro"],
    works: ["Bartók – Música para cuerdas, percusión y celesta", "Charlie Parker – pasajes"],
    relations: ["Modo IV del menor melódico. Funciona sobre dom7b5 y bII7 (sustitución tritonal)."],
    level: 6,
  },
  {
    id: "mixolydianb6",
    name: "Mixolidio b6",
    aliases: ["Hindú", "Modo V del menor melódico"],
    family: "melodicMinorModes",
    intervals: [0, 2, 4, 5, 7, 8, 10],
    formula: "1 - 2 - 3 - 4 - 5 - b6 - b7",
    description: "Mixolidio con sexta menor. Sonoridad dominante con tensión b13.",
    origin: "Modo V del menor melódico. Acorde-base de la dominante con b13 en jazz.",
    genres: ["Jazz modal", "Música hindú"],
    works: ["Jazz fusión contemporáneo"],
    relations: ["Modo V del menor melódico."],
    level: 6,
  },
  {
    id: "locrian2",
    name: "Locrio #2",
    aliases: ["Semilocrio", "Modo VI del menor melódico"],
    family: "melodicMinorModes",
    intervals: [0, 2, 3, 5, 6, 8, 10],
    formula: "1 - 2 - b3 - 4 - b5 - b6 - b7",
    description: "Locrio con segunda mayor. Menos colapsado que el locrio puro.",
    origin: "Modo VI del menor melódico. Escala del semidisminuido (ø7) en jazz moderno.",
    genres: ["Jazz moderno", "Bebop avanzado"],
    works: ["ii-V-i menores en bebop"],
    relations: ["Modo VI del menor melódico. Sobre acorde ø7."],
    level: 6,
  },
  {
    id: "altered",
    name: "Alterada",
    aliases: ["Súper locrio", "Modo VII del menor melódico", "Diminished whole-tone"],
    family: "melodicMinorModes",
    intervals: [0, 1, 3, 4, 6, 8, 10],
    formula: "1 - b2 - b3 - 3 - b5 - #5 - b7",
    description:
      "Todas las extensiones del dominante alteradas (b9, #9, b5/#11, #5/b13). La escala del dominante en jazz moderno.",
    origin:
      "Modo VII del menor melódico. Sistematizada por Bill Evans, John Coltrane y la escuela bebop tardía.",
    genres: ["Jazz moderno", "Bebop", "Postbop"],
    works: ["Coltrane – Giant Steps (improvisación)", "Bill Evans – cualquier solo sobre V7alt"],
    relations: ["Es la escala alterada del dominante. Modo VII del menor melódico."],
    level: 6,
  },

  // ===== MODOS DEL MENOR ARMÓNICO =====
  {
    id: "locrian6",
    name: "Locrio #6",
    aliases: ["Modo II del menor armónico"],
    family: "harmonicMinorModes",
    intervals: [0, 1, 3, 5, 6, 9, 10],
    formula: "1 - b2 - b3 - 4 - b5 - 6 - b7",
    description: "Locrio con sexta mayor. Color particular, mezcla de tensión y luminosidad.",
    origin: "Modo II del menor armónico.",
    genres: ["Repertorio modal", "Jazz exploratorio"],
    works: ["Repertorio del XX"],
    relations: ["Modo II del menor armónico."],
    level: 7,
  },
  {
    id: "ionianAug",
    name: "Jónico aumentado",
    aliases: ["Modo III del menor armónico", "Ionian #5"],
    family: "harmonicMinorModes",
    intervals: [0, 2, 4, 5, 8, 9, 11],
    formula: "1 - 2 - 3 - 4 - #5 - 6 - 7",
    description: "Mayor con quinta aumentada. Sonoridad onírica.",
    origin: "Modo III del menor armónico.",
    genres: ["Jazz modal", "Música del XX"],
    works: ["Repertorio jazz moderno"],
    relations: ["Modo III del menor armónico."],
    level: 7,
  },
  {
    id: "dorianS4",
    name: "Dórico #4",
    aliases: ["Ucraniano", "Rumano menor", "Mi Sheberach", "Modo IV del menor armónico"],
    family: "harmonicMinorModes",
    intervals: [0, 2, 3, 6, 7, 9, 10],
    formula: "1 - 2 - b3 - #4 - 5 - 6 - b7",
    description: "Dórico con cuarta aumentada. Sonoridad del klezmer y la música rumana/ucraniana.",
    origin:
      "Modo IV del menor armónico. Tradición judía askenazi (Mi Sheberach), rumana y ucraniana.",
    genres: ["Klezmer", "Folk rumano", "Folk ucraniano", "Música hebrea"],
    works: ["Tradición klezmer", "Bartók – temas folklóricos"],
    relations: ["Modo IV del menor armónico."],
    level: 7,
  },
  {
    id: "phrygianDom",
    name: "Frigio dominante",
    aliases: [
      "Andaluz",
      "Spanish Phrygian",
      "Freygish",
      "Ahava Rabbah",
      "Hijaz-Nahawand",
      "Bhairav (raga)",
      "Modo V del menor armónico",
    ],
    family: "harmonicMinorModes",
    intervals: [0, 1, 4, 5, 7, 8, 10],
    formula: "1 - b2 - 3 - 4 - 5 - b6 - b7",
    description:
      "Frigio con tercera mayor. La escala más usada globalmente: España, Magreb, Levante, Balcanes, Asia central, India norte.",
    origin:
      "Modo V del menor armónico. Sus rotaciones culturales son innumerables: andaluz, klezmer, hijaz árabe, raga Bhairav, escala húngara, etc.",
    genres: [
      "Flamenco modal",
      "Música árabe-andalusí",
      "Klezmer",
      "Música hindú clásica (raga Bhairav)",
      "Metal neoclásico",
    ],
    works: [
      "Paco de Lucía – Entre dos aguas",
      "Dick Dale – Misirlou",
      "Iron Maiden – Powerslave",
      "Tradición klezmer (cualquier freylach)",
    ],
    relations: [
      "Modo V del menor armónico. Diferente del frigio diatónico por la 3ª mayor.",
      "Es 'gemelo cultural' del hijaz árabe (en aproximación al temperamento igual).",
    ],
    level: 5,
  },
  {
    id: "lydian2",
    name: "Lidio #2",
    aliases: ["Modo VI del menor armónico"],
    family: "harmonicMinorModes",
    intervals: [0, 3, 4, 6, 7, 9, 11],
    formula: "1 - #2 - 3 - #4 - 5 - 6 - 7",
    description: "Lidio con segunda aumentada. Sonoridad exótica oriental.",
    origin: "Modo VI del menor armónico.",
    genres: ["Música del XX", "Folk centroeuropeo"],
    works: ["Repertorio postonal"],
    relations: ["Modo VI del menor armónico."],
    level: 7,
  },
  {
    id: "superLocrianBB7",
    name: "Súper locrio bb7",
    aliases: ["Locrio b4 bb7", "Modo VII del menor armónico"],
    family: "harmonicMinorModes",
    intervals: [0, 1, 3, 4, 6, 8, 9],
    formula: "1 - b2 - b3 - b4 - b5 - b6 - bb7",
    description: "Locrio con cuarta y séptima bemolizadas. Sonoridad extremadamente oscura.",
    origin: "Modo VII del menor armónico. Usado como escala del dom7b9 con tensiones.",
    genres: ["Jazz moderno"],
    works: ["Repertorio postbop"],
    relations: ["Modo VII del menor armónico."],
    level: 8,
  },

  // ===== PENTATÓNICAS =====
  {
    id: "majPent",
    name: "Pentatónica mayor",
    aliases: ["Cinco-tonos mayor", "Mela 29 (sin 4 y 7)"],
    family: "pentatonic",
    intervals: [0, 2, 4, 7, 9],
    formula: "1 - 2 - 3 - 5 - 6",
    description: "Mayor sin tensiones (sin 4 y sin 7). Universalmente consonante.",
    origin:
      "Presente en folklores de todos los continentes: gaélico, africano, andino, asiático.",
    genres: ["Folk", "Country", "Blues mayor", "Música tradicional china/japonesa"],
    works: ["Amazing Grace", "Dvořák – Sinfonía del Nuevo Mundo"],
    relations: ["Es subconjunto del mayor. Sus 5 rotaciones dan distintas culturas folklóricas."],
    level: 2,
  },
  {
    id: "minPent",
    name: "Pentatónica menor",
    aliases: ["Cinco-tonos menor"],
    family: "pentatonic",
    intervals: [0, 3, 5, 7, 10],
    formula: "1 - b3 - 4 - 5 - b7",
    description: "Subconjunto del menor natural. Base universal del blues y rock.",
    origin: "Modo V de la pentatónica mayor. Universal en blues, rock y folk pentatónico.",
    genres: ["Blues", "Rock", "Folk", "Jazz"],
    works: ["B.B. King – cualquier solo", "Eric Clapton – cualquier blues"],
    relations: ["Modo V de la pentatónica mayor. Añadirle b5 da la pentatónica de blues."],
    level: 2,
  },
  {
    id: "bluesMaj",
    name: "Blues mayor",
    aliases: ["Pentatónica mayor + b3"],
    family: "pentatonic",
    intervals: [0, 2, 3, 4, 7, 9],
    formula: "1 - 2 - b3 - 3 - 5 - 6",
    description: "Pentatónica mayor con blue note (b3 → 3).",
    origin: "Blues clásico mayor. Versión más alegre del blues.",
    genres: ["Blues mayor", "Country blues"],
    works: ["B.B. King – Sweet Little Angel (versión mayor)"],
    relations: ["Variante de blues sobre pentatónica mayor."],
    level: 3,
  },
  {
    id: "bluesMin",
    name: "Blues menor",
    aliases: ["Pentatónica menor + b5"],
    family: "pentatonic",
    intervals: [0, 3, 5, 6, 7, 10],
    formula: "1 - b3 - 4 - b5 - 5 - b7",
    description: "Pentatónica menor con blue note (b5).",
    origin: "Blues clásico. Universal en el blues, rock y jazz.",
    genres: ["Blues", "Rock blues", "Jazz blues"],
    works: ["Cream – Crossroads", "Howlin' Wolf – Smokestack Lightning"],
    relations: ["Variante de blues sobre pentatónica menor."],
    level: 3,
  },
  {
    id: "hirajoshi",
    name: "Hirajoshi",
    aliases: ["Pentatónica japonesa"],
    family: "pentatonic",
    intervals: [0, 2, 3, 7, 8],
    formula: "1 - 2 - b3 - 5 - b6",
    description: "Pentatónica japonesa con b6: sonoridad contemplativa, koto, shamisen.",
    origin: "Música tradicional japonesa para koto.",
    genres: ["Música tradicional japonesa", "Cine de samuráis"],
    works: ["Toru Takemitsu – obras", "Bandas sonoras japonesas"],
    relations: ["Comparte tetracordes con hirajoshi y kumoi."],
    level: 4,
  },
  {
    id: "kumoi",
    name: "Kumoi",
    aliases: ["Pentatónica japonesa (variante)"],
    family: "pentatonic",
    intervals: [0, 2, 3, 7, 9],
    formula: "1 - 2 - b3 - 5 - 6",
    description: "Pentatónica con 6 mayor. Variante luminosa de hirajoshi.",
    origin: "Música japonesa tradicional. Variante de hirajoshi.",
    genres: ["Música tradicional japonesa"],
    works: ["Repertorio koto clásico"],
    relations: ["Rotación de la familia pentatónica japonesa."],
    level: 4,
  },
  {
    id: "insen",
    name: "In sen",
    aliases: ["Pentatónica japonesa", "Pentatónica oriental"],
    family: "pentatonic",
    intervals: [0, 1, 5, 7, 10],
    formula: "1 - b2 - 4 - 5 - b7",
    description: "Pentatónica con b2: sonoridad oriental tensa.",
    origin: "Música tradicional japonesa.",
    genres: ["Música tradicional japonesa"],
    works: ["Repertorio shakuhachi"],
    relations: ["Rotación de hirajoshi."],
    level: 4,
  },
  {
    id: "iwato",
    name: "Iwato",
    aliases: ["Pentatónica oriental"],
    family: "pentatonic",
    intervals: [0, 1, 5, 6, 10],
    formula: "1 - b2 - 4 - b5 - b7",
    description: "Pentatónica oriental con b2 y b5.",
    origin: "Música tradicional japonesa.",
    genres: ["Música tradicional japonesa"],
    works: ["Repertorio koto"],
    relations: ["Familia pentatónica oriental."],
    level: 5,
  },
  {
    id: "pelog",
    name: "Pelog",
    aliases: ["Gamelán indonesio (aprox.)"],
    family: "pentatonic",
    intervals: [0, 1, 3, 7, 8],
    formula: "1 - b2 - b3 - 5 - b6",
    description: "Aproximación al sistema pelog del gamelán balinés/javanés.",
    origin:
      "Sistema indonesio. Su afinación original es microtonal; aquí se aproxima al temperamento igual.",
    genres: ["Gamelán"],
    works: ["Repertorio de gamelán balinés", "Influencias en Debussy y Britten"],
    relations: ["Aproximación temperada de un sistema microtonal."],
    level: 5,
  },

  // ===== HEXÁFONAS =====
  {
    id: "wholeTone",
    name: "Tonos enteros",
    aliases: ["Hexáfona", "MTL I de Messiaen"],
    family: "hexatonic",
    intervals: [0, 2, 4, 6, 8, 10],
    formula: "1 - 2 - 3 - #4 - #5 - b7",
    description: "Seis tonos enteros consecutivos. Total simetría; no establece tónica.",
    origin:
      "Debussy la sistematiza como sonoridad de tonalidad suspendida. Messiaen la incluye como MTL I.",
    genres: ["Impresionismo", "Música del XX"],
    works: ["Debussy – Voiles", "Mussorgsky/Ravel – Promenade", "Stevie Wonder – You Are the Sunshine of My Life (puente)"],
    relations: ["Solo dos transposiciones distintas. Es MTL I de Messiaen."],
    level: 4,
  },
  {
    id: "prometheus",
    name: "Prometeo",
    aliases: ["Acorde místico de Scriabin"],
    family: "hexatonic",
    intervals: [0, 2, 4, 6, 9, 10],
    formula: "1 - 2 - 3 - #4 - 6 - b7",
    description: "Hexáfona de Scriabin, base del 'acorde místico' de su obra tardía.",
    origin: "Alexander Scriabin la teoriza para su Prometeo, Op. 60 (1910).",
    genres: ["Postromanticismo ruso", "Música del XX"],
    works: ["Scriabin – Prometheus: Poema del fuego", "Scriabin – Sonatas tardías"],
    relations: ["Subconjunto del lidio dominante con la 5 omitida."],
    level: 6,
  },
  {
    id: "augmented",
    name: "Aumentada",
    aliases: ["Hexáfona aumentada"],
    family: "hexatonic",
    intervals: [0, 3, 4, 7, 8, 11],
    formula: "1 - b3 - 3 - 5 - #5 - 7",
    description: "Dos tríadas aumentadas alternadas. Sonoridad simétrica del jazz moderno.",
    origin: "Sistematizada en jazz contemporáneo (Coltrane, Patterns).",
    genres: ["Jazz moderno"],
    works: ["Coltrane – patrones aumentados"],
    relations: ["Solo cuatro transposiciones distintas (simetría aumentada)."],
    level: 6,
  },
  {
    id: "tritone",
    name: "Tritono",
    aliases: ["Hexáfona simétrica del tritono"],
    family: "hexatonic",
    intervals: [0, 1, 4, 6, 7, 10],
    formula: "1 - b2 - 3 - b5 - 5 - b7",
    description: "Dos dominantes a distancia de tritono (sustitución tritonal).",
    origin: "Jazz moderno. Resultado de superponer dos acordes 7 a distancia de #4.",
    genres: ["Jazz moderno", "Música del XX"],
    works: ["Repertorio postbop"],
    relations: ["Solo seis transposiciones distintas."],
    level: 7,
  },

  // ===== OCTATÓNICAS Y BEBOP =====
  {
    id: "dimWH",
    name: "Disminuida (W-H)",
    aliases: ["Octatónica tono-semitono"],
    family: "octatonic",
    intervals: [0, 2, 3, 5, 6, 8, 9, 11],
    formula: "1 - 2 - b3 - 4 - b5 - b6 - 6 - 7",
    description: "Tono-semitono alternados. Escala de tónicas menores con tensiones cromáticas.",
    origin:
      "Rimsky-Korsakov la introduce sistemáticamente. Stravinsky la usa en La consagración de la primavera.",
    genres: ["Música rusa", "Jazz moderno"],
    works: ["Stravinsky – La consagración de la primavera", "Rimsky-Korsakov – Antar"],
    relations: ["MTL II de Messiaen. Solo tres transposiciones distintas."],
    level: 5,
  },
  {
    id: "dimHW",
    name: "Disminuida (H-W)",
    aliases: ["Octatónica semitono-tono", "Diminished dominant"],
    family: "octatonic",
    intervals: [0, 1, 3, 4, 6, 7, 9, 10],
    formula: "1 - b2 - b3 - 3 - b5 - 5 - 6 - b7",
    description: "Semitono-tono alternados. Escala del dominante en jazz moderno.",
    origin: "Stravinsky, Bartók. Sistematizada en jazz para dominantes alterados.",
    genres: ["Jazz moderno", "Música del XX"],
    works: ["Stravinsky – Pájaro de fuego (motivos del Pájaro)"],
    relations: ["Rotación de la W-H. MTL II de Messiaen."],
    level: 5,
  },
  {
    id: "chromatic",
    name: "Cromática",
    aliases: ["12 sonidos"],
    family: "octatonic",
    intervals: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    formula: "1 - b2 - 2 - b3 - 3 - 4 - b5 - 5 - b6 - 6 - b7 - 7",
    description: "Los doce sonidos del temperamento igual.",
    origin: "Universal. Recurso melódico y armónico transversal.",
    genres: ["Toda la tradición occidental"],
    works: ["Bach – Fantasía cromática y fuga", "Schoenberg – obras dodecafónicas"],
    relations: ["Contiene todas las demás escalas como subconjuntos."],
    level: 1,
  },
  {
    id: "bebopMaj",
    name: "Bebop mayor",
    aliases: ["Mayor con #5 de paso"],
    family: "octatonic",
    intervals: [0, 2, 4, 5, 7, 8, 9, 11],
    formula: "1 - 2 - 3 - 4 - 5 - #5 - 6 - 7",
    description: "Mayor con un cromatismo adicional entre 5 y 6 (b6/#5).",
    origin: "Jazz bebop. Charlie Parker, Dizzy Gillespie.",
    genres: ["Bebop", "Jazz moderno"],
    works: ["Charlie Parker – cualquier solo bebop"],
    relations: ["Su cromatismo añadido equilibra ritmicamente la línea improvisada."],
    level: 3,
  },
  {
    id: "bebopDom",
    name: "Bebop dominante",
    aliases: ["Mixolidio con 7 de paso"],
    family: "octatonic",
    intervals: [0, 2, 4, 5, 7, 9, 10, 11],
    formula: "1 - 2 - 3 - 4 - 5 - 6 - b7 - 7",
    description: "Mixolidio con séptima mayor agregada como cromatismo de paso.",
    origin: "Jazz bebop. La escala bebop más común.",
    genres: ["Bebop"],
    works: ["Charlie Parker – Donna Lee", "Dizzy Gillespie – cualquier solo"],
    relations: ["Para dominantes en cualquier ii-V-I."],
    level: 3,
  },
  {
    id: "bebopDorian",
    name: "Bebop dórico",
    aliases: ["Dórico con 3 de paso"],
    family: "octatonic",
    intervals: [0, 2, 3, 4, 5, 7, 9, 10],
    formula: "1 - 2 - b3 - 3 - 4 - 5 - 6 - b7",
    description: "Dórico con tercera mayor de paso.",
    origin: "Jazz bebop.",
    genres: ["Bebop"],
    works: ["Repertorio bebop"],
    relations: ["Para acordes m7 sobre dórico."],
    level: 4,
  },
  {
    id: "bebopMelMin",
    name: "Bebop melódico menor",
    aliases: ["Menor melódico con #5 de paso"],
    family: "octatonic",
    intervals: [0, 2, 3, 5, 7, 8, 9, 11],
    formula: "1 - 2 - b3 - 4 - 5 - #5 - 6 - 7",
    description: "Menor melódico ascendente con cromatismo de paso.",
    origin: "Jazz moderno postbop.",
    genres: ["Jazz moderno"],
    works: ["Repertorio postbop"],
    relations: ["Para acordes mMaj7."],
    level: 4,
  },
  {
    id: "spanish8",
    name: "Española de 8 sonidos",
    aliases: ["Escala andaluza extendida"],
    family: "octatonic",
    intervals: [0, 1, 3, 4, 5, 6, 8, 10],
    formula: "1 - b2 - b3 - 3 - 4 - b5 - b6 - b7",
    description:
      "Octatónica de carácter andaluz, mezcla frigia dominante con cromatismos del tetracordo superior.",
    origin: "Persichetti la cataloga entre las escalas sintéticas.",
    genres: ["Música del XX", "Flamenco moderno"],
    works: ["Repertorio postonal"],
    relations: ["Combina frigio dominante con notas cromáticas."],
    level: 7,
  },

  // ===== MODOS DE MESSIAEN =====
  {
    id: "mtl1",
    name: "MTL I",
    aliases: ["Tonos enteros"],
    family: "messiaen",
    intervals: [0, 2, 4, 6, 8, 10],
    formula: "T - T - T - T - T - T",
    description: "Modo I de Messiaen: tonos enteros. Solo 2 transposiciones distintas.",
    origin: "Olivier Messiaen los teoriza en Technique de mon langage musical (1944).",
    genres: ["Música del XX"],
    works: ["Messiaen – Cuarteto para el fin de los tiempos"],
    relations: ["Coincide con la hexáfona de tonos enteros."],
    level: 4,
  },
  {
    id: "mtl2",
    name: "MTL II",
    aliases: ["Octatónica"],
    family: "messiaen",
    intervals: [0, 1, 3, 4, 6, 7, 9, 10],
    formula: "S - T - S - T - S - T - S - T",
    description: "Modo II de Messiaen: octatónica H-W. Solo 3 transposiciones distintas.",
    origin: "Messiaen, sistematizando lo que Rimsky-Korsakov y Stravinsky usaban.",
    genres: ["Música del XX"],
    works: ["Messiaen – Modes de valeurs et d'intensités"],
    relations: ["Coincide con la octatónica H-W."],
    level: 5,
  },
  {
    id: "mtl3",
    name: "MTL III",
    aliases: ["Eneatónico simétrico"],
    family: "messiaen",
    intervals: [0, 2, 3, 4, 6, 7, 8, 10, 11],
    formula: "T - S - S - T - S - S - T - S - S",
    description: "Nueve sonidos divididos en tres grupos simétricos.",
    origin: "Messiaen.",
    genres: ["Música del XX"],
    works: ["Messiaen – Visions de l'Amen"],
    relations: ["Cuatro transposiciones distintas."],
    level: 7,
  },
  {
    id: "mtl4",
    name: "MTL IV",
    aliases: ["Octatónico de Messiaen IV"],
    family: "messiaen",
    intervals: [0, 1, 2, 5, 6, 7, 8, 11],
    formula: "S - S - +T+S - S - S - S - +T+S - S",
    description: "Modo IV de Messiaen: estructura simétrica con tritono.",
    origin: "Messiaen.",
    genres: ["Música del XX"],
    works: ["Messiaen – Couleurs de la cité céleste"],
    relations: ["Seis transposiciones distintas."],
    level: 8,
  },
  {
    id: "mtl5",
    name: "MTL V",
    aliases: ["Hexáfono de Messiaen V"],
    family: "messiaen",
    intervals: [0, 1, 5, 6, 7, 11],
    formula: "S - +T+S - S - S - +T+S - S",
    description: "Modo V de Messiaen: seis sonidos con doble tritono.",
    origin: "Messiaen.",
    genres: ["Música del XX"],
    works: ["Messiaen – Quatuor"],
    relations: ["Seis transposiciones distintas."],
    level: 8,
  },
  {
    id: "mtl6",
    name: "MTL VI",
    aliases: ["Octatónico de Messiaen VI"],
    family: "messiaen",
    intervals: [0, 2, 4, 5, 6, 8, 10, 11],
    formula: "T - T - S - S - T - T - S - S",
    description: "Modo VI de Messiaen.",
    origin: "Messiaen.",
    genres: ["Música del XX"],
    works: ["Messiaen – obras tardías"],
    relations: ["Seis transposiciones distintas."],
    level: 8,
  },
  {
    id: "mtl7",
    name: "MTL VII",
    aliases: ["Decatónico de Messiaen"],
    family: "messiaen",
    intervals: [0, 1, 2, 3, 5, 6, 7, 8, 9, 11],
    formula: "S - S - S - T - S - S - S - S - T - S",
    description: "Modo VII de Messiaen: diez sonidos.",
    origin: "Messiaen.",
    genres: ["Música del XX"],
    works: ["Messiaen – obras tardías"],
    relations: ["Seis transposiciones distintas. Casi cromático."],
    level: 8,
  },

  // ===== ESCALAS EXÓTICAS Y SINTÉTICAS =====
  {
    id: "doubleHarmonic",
    name: "Doble armónica",
    aliases: ["Bizantina", "Húngara mayor"],
    family: "synthetic",
    intervals: [0, 1, 4, 5, 7, 8, 11],
    formula: "1 - b2 - 3 - 4 - 5 - b6 - 7",
    description: "Dos segundas aumentadas (b2-3 y b6-7). Sonoridad doblemente oriental.",
    origin:
      "Tradición bizantina, música árabe (maqam Hijaz-Nahawand), folklore húngaro.",
    genres: ["Música bizantina", "Folklore húngaro", "Metal exótico"],
    works: ["Steve Vai – pasajes exóticos", "Folklore balcánico"],
    relations: ["Comparte estructura con maqam Hijaz-Nahawand. Sus modos incluyen la húngara menor."],
    level: 6,
  },
  {
    id: "hungarianMin",
    name: "Húngara menor",
    aliases: ["Doble armónica menor", "Gitana menor"],
    family: "synthetic",
    intervals: [0, 2, 3, 6, 7, 8, 11],
    formula: "1 - 2 - b3 - #4 - 5 - b6 - 7",
    description: "Menor con #4 y 7 mayor. Dos segundas aumentadas (b3-#4 y b6-7).",
    origin: "Música tradicional húngara, romaní. Liszt la sistematiza en sus rapsodias.",
    genres: ["Folklore húngaro", "Música clásica romántica", "Romaní"],
    works: ["Liszt – Rapsodias húngaras", "Brahms – Danzas húngaras"],
    relations: ["Es el modo IV de la doble armónica."],
    level: 6,
  },
  {
    id: "neapolitanMin",
    name: "Napolitana menor",
    aliases: ["Phrygian #7"],
    family: "synthetic",
    intervals: [0, 1, 3, 5, 7, 8, 11],
    formula: "1 - b2 - b3 - 4 - 5 - b6 - 7",
    description: "Frigio con sensible. Resultado del acorde napolitano elevado a escala.",
    origin: "Escuela napolitana del XVIII. Verdi, Donizetti.",
    genres: ["Ópera italiana del XIX"],
    works: ["Verdi – Otello (recursos napolitanos)"],
    relations: ["Variante de la frigia con sensible alzada."],
    level: 7,
  },
  {
    id: "neapolitanMaj",
    name: "Napolitana mayor",
    aliases: ["Mayor con b2"],
    family: "synthetic",
    intervals: [0, 1, 3, 5, 7, 9, 11],
    formula: "1 - b2 - b3 - 4 - 5 - 6 - 7",
    description: "Menor melódico ascendente con b2. Resultado de la napolitana sobre tónica menor.",
    origin: "Sistematizada en el barroco italiano.",
    genres: ["Ópera italiana", "Postonal"],
    works: ["Repertorio operístico"],
    relations: ["Variante del menor melódico con b2."],
    level: 7,
  },
  {
    id: "oriental",
    name: "Oriental",
    aliases: ["Persichetti Oriental"],
    family: "synthetic",
    intervals: [0, 1, 4, 5, 6, 9, 10],
    formula: "1 - b2 - 3 - 4 - b5 - 6 - b7",
    description: "Escala sintética con doble tetracordo oriental. Persichetti la cataloga.",
    origin: "Sintética del XX. Persichetti.",
    genres: ["Música del XX"],
    works: ["Persichetti – Harmonía del siglo XX (tratado)"],
    relations: ["Persichetti la cataloga junto con la doble armónica."],
    level: 7,
  },
  {
    id: "enigmatic",
    name: "Enigmática",
    aliases: ["Escala de Verdi"],
    family: "synthetic",
    intervals: [0, 1, 4, 6, 8, 10, 11],
    formula: "1 - b2 - 3 - #4 - #5 - #6 - 7",
    description: "Escala que Verdi propuso como ejercicio armónico (1888).",
    origin: "Verdi la publica como reto compositivo en la Gazzetta Musicale.",
    genres: ["Música del XX"],
    works: ["Verdi – Ave Maria scala enigmatica"],
    relations: ["Mezcla tonos enteros con cromatismos cadenciales."],
    level: 8,
  },
  {
    id: "locrianMaj",
    name: "Locria mayor",
    aliases: ["Persichetti Locria mayor"],
    family: "synthetic",
    intervals: [0, 2, 4, 5, 6, 8, 10],
    formula: "1 - 2 - 3 - 4 - b5 - b6 - b7",
    description: "Locrio con tercera mayor. Persichetti la cataloga.",
    origin: "Sintética del XX.",
    genres: ["Música del XX"],
    works: ["Persichetti – tratado"],
    relations: ["Es el quinto modo del menor armónico con b6."],
    level: 7,
  },
  {
    id: "lydianMin",
    name: "Lidia menor",
    aliases: ["Persichetti Lidia menor"],
    family: "synthetic",
    intervals: [0, 2, 4, 6, 7, 8, 10],
    formula: "1 - 2 - 3 - #4 - 5 - b6 - b7",
    description: "Lidio con b6 y b7.",
    origin: "Sintética. Cataloga Persichetti.",
    genres: ["Música del XX"],
    works: ["Repertorio del XX"],
    relations: ["Comparte tetracordo inferior con lidio."],
    level: 7,
  },
  {
    id: "persian",
    name: "Persa",
    aliases: ["Persian scale"],
    family: "synthetic",
    intervals: [0, 1, 4, 5, 6, 8, 11],
    formula: "1 - b2 - 3 - 4 - b5 - b6 - 7",
    description: "Escala persa: doble segunda aumentada con b5.",
    origin: "Tradición persa (Dastgah). Aproximación temperada.",
    genres: ["Música persa tradicional"],
    works: ["Repertorio persa"],
    relations: ["Aproximación temperada de modos del dastgah persa."],
    level: 7,
  },
  {
    id: "mongolian",
    name: "Mongoliana",
    aliases: ["Pentatónica mongol"],
    family: "synthetic",
    intervals: [0, 2, 4, 7, 9],
    formula: "1 - 2 - 3 - 5 - 6",
    description: "Coincide con la pentatónica mayor; presente en folklore mongol y de Asia central.",
    origin: "Música tradicional mongola.",
    genres: ["Música tradicional mongola"],
    works: ["Cantos garganta (khoomei)"],
    relations: ["Idéntica intervalicamente a la pentatónica mayor."],
    level: 4,
  },

  // ===== APROXIMACIONES NO-OCCIDENTALES =====
  // Nota: estas son aproximaciones al temperamento igual de tradiciones
  // que originalmente usan microtonalidad. La tarjeta lo aclarará.
  {
    id: "hijaz",
    name: "Hijaz",
    aliases: ["Maqam Hijaz (aprox.)"],
    family: "worldApprox",
    intervals: [0, 1, 4, 5, 7, 8, 10],
    formula: "1 - b2 - 3 - 4 - 5 - b6 - b7",
    description:
      "Aproximación temperada del maqam Hijaz árabe. La 3 'real' es ligeramente más baja (neutral).",
    origin:
      "Sistema árabe-andalusí, Levante mediterráneo, Magreb. Equivale aprox. al frigio dominante.",
    genres: ["Música árabe", "Música andalusí", "Música turca"],
    works: ["Repertorio del maqam Hijaz"],
    relations: ["Coincide intervalicamente con el frigio dominante en temperamento igual."],
    level: 5,
  },
  {
    id: "bayati",
    name: "Bayati",
    aliases: ["Maqam Bayati (aprox.)"],
    family: "worldApprox",
    intervals: [0, 1, 3, 5, 7, 8, 10],
    formula: "1 - b2 - b3 - 4 - 5 - b6 - b7",
    description:
      "Aproximación del maqam Bayati. La 'b2 real' es neutral (sik), no semitono exacto.",
    origin: "Maqam árabe muy difundido. Aproximación temperada inexacta.",
    genres: ["Música árabe"],
    works: ["Tradición egipcia y levantina"],
    relations: ["Coincide intervalicamente con el frigio."],
    level: 6,
  },
  {
    id: "rast",
    name: "Rast",
    aliases: ["Maqam Rast (aprox.)"],
    family: "worldApprox",
    intervals: [0, 2, 4, 5, 7, 9, 10],
    formula: "1 - 2 - 3 - 4 - 5 - 6 - b7",
    description:
      "Aproximación del maqam Rast. Su 3ª 'real' es neutral (un cuarto de tono debajo de la 3 mayor).",
    origin: "Maqam fundamental de la música árabe.",
    genres: ["Música árabe", "Música turca"],
    works: ["Repertorio Rast"],
    relations: ["Coincide intervalicamente con el mixolidio en temperamento igual."],
    level: 5,
  },
  {
    id: "bhairav",
    name: "Bhairav",
    aliases: ["Raga Bhairav (aprox.)"],
    family: "worldApprox",
    intervals: [0, 1, 4, 5, 7, 8, 11],
    formula: "1 - b2 - 3 - 4 - 5 - b6 - 7",
    description: "Raga de la mañana (sandhi prakash). Aproximación al raga clásico hindú.",
    origin:
      "Música clásica hindostaní (India norte). Raga del amanecer.",
    genres: ["Música clásica hindostaní"],
    works: ["Tradición de raga matinal"],
    relations: ["Coincide intervalicamente con la doble armónica."],
    level: 6,
  },
  {
    id: "yaman",
    name: "Yaman",
    aliases: ["Raga Yaman (aprox.)", "Kalyan"],
    family: "worldApprox",
    intervals: [0, 2, 4, 6, 7, 9, 11],
    formula: "1 - 2 - 3 - #4 - 5 - 6 - 7",
    description: "Raga vespertino fundamental.",
    origin: "Música clásica hindostaní. Raga de la tarde-noche.",
    genres: ["Música clásica hindostaní"],
    works: ["Tradición de raga vespertino"],
    relations: ["Coincide intervalicamente con el lidio."],
    level: 4,
  },
];

export function getScale(id) {
  return SCALES.find((s) => s.id === id);
}

export function scalesByFamily(family) {
  return SCALES.filter((s) => s.family === family);
}

export function scalesByLevel(maxLevel) {
  return SCALES.filter((s) => s.level <= maxLevel);
}
